[project]
name = "quill"
version = "0.1.0"
description = "A split-file transcription tool using faster-whisper"
readme = "Readme.md"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper",
    "click",
    "yt-dlp",
    "nvidia-cudnn-cu12>=9.17.1.4",
    "nvidia-cudnn-cu11>=9.10.2.21",
]

[project.scripts]
quill = "app.cli.commands:transcribe"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]
